/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.ComparadoresE;
import Objetos.CrudE;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class BuscarE extends javax.swing.JInternalFrame {

    /**
     * Creates new form MEstudiantes
     */
    public BuscarE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        btnBuscarsexo = new javax.swing.JButton();
        mayor12 = new javax.swing.JButton();
        menor12 = new javax.swing.JButton();
        cmbSexoE = new javax.swing.JComboBox<>();
        btnZona = new javax.swing.JButton();
        cmbxZona = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MostrarEstudiantes");
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("Buscar Datos de Estudiantes en la Base");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 30, 590, 40);

        datos.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 850, 350);

        btnBuscarsexo.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        btnBuscarsexo.setText("Buscar Sexo");
        btnBuscarsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarsexoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarsexo);
        btnBuscarsexo.setBounds(70, 460, 120, 47);

        mayor12.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        mayor12.setText("Mayores a 12"); // NOI18N
        mayor12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayor12ActionPerformed(evt);
            }
        });
        getContentPane().add(mayor12);
        mayor12.setBounds(290, 470, 140, 40);

        menor12.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        menor12.setText("Menores a 12");
        menor12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menor12ActionPerformed(evt);
            }
        });
        getContentPane().add(menor12);
        menor12.setBounds(450, 470, 140, 39);

        cmbSexoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSexoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(cmbSexoE);
        cmbSexoE.setBounds(210, 470, 50, 30);

        btnZona.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        btnZona.setText("Buscar Zona");
        btnZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaActionPerformed(evt);
            }
        });
        getContentPane().add(btnZona);
        btnZona.setBounds(620, 460, 120, 47);

        cmbxZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "U" }));
        getContentPane().add(cmbxZona);
        cmbxZona.setBounds(760, 470, 50, 30);

        setBounds(340, 110, 879, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarsexoActionPerformed
        String sexo =cmbSexoE.getSelectedItem().toString();
        ComparadoresE buscar = new ComparadoresE();
        buscar.femoMas(datos, sexo);
    }//GEN-LAST:event_btnBuscarsexoActionPerformed

    private void mayor12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayor12ActionPerformed
        final int edad=12;
        ComparadoresE buscar = new ComparadoresE();
        buscar.nioAd(datos, edad);
    }//GEN-LAST:event_mayor12ActionPerformed

    private void menor12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menor12ActionPerformed
        final int edad=11;
        ComparadoresE buscar = new ComparadoresE();
        buscar.nioAd(datos, edad);
    }//GEN-LAST:event_menor12ActionPerformed

    private void btnZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaActionPerformed
        String zona =cmbxZona.getSelectedItem().toString();
        ComparadoresE buscar = new ComparadoresE();
        buscar.ruroUrb(datos, zona);
    }//GEN-LAST:event_btnZonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarsexo;
    public javax.swing.JButton btnZona;
    public javax.swing.JComboBox<String> cmbSexoE;
    public javax.swing.JComboBox<String> cmbxZona;
    public javax.swing.JTable datos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mayor12;
    private javax.swing.JButton menor12;
    // End of variables declaration//GEN-END:variables
}
